### PR TITLE
Funny webhook for fake admin page

### PR DESCRIPTION
**Pull request by Craftzman7**
Adds a funny admin webhook message for when someone tries to access the fake admin page with the wrong password. I was contemplating pushing this to the public webhook channel (which can be easily done).

### CODE REVIEW

**Review by vtheskeleton — CHANGES_REQUESTED** [review]
First of all
Await in a non async function? are you high?

secondly,
A webhook request every time someone makes a get request to an endpoint? no thanks..

thirdly, youre printing the entire user OBJECT, this will either spew a shitload of information onto discord (might even pass the character limit) or just ends up as [object Object]

conclusion:
You are high

**Comment by Vukkyy** [comment]
> A webhook request every time someone makes a get request to an endpoint? no thanks..

Code redemptions would like to know your location.

**Comment by vtheskeleton** [comment]
> > A webhook request every time someone makes a get request to an endpoint? no thanks..
> 
> Code redemptions would like to know your location.

mmMmmMmMmmMmMmmMm we should make those only trigger on valid codes

**Comment by Craftzman7** [comment]
> > A webhook request every time someone makes a get request to an endpoint? no thanks..
> 
> Code redemptions would like to know your location.

LOL

**Comment by Craftzman7** [comment]
In that case I kinda wanna unmark this as a draft.
We could set a cookie that'll log it but that's not a good thing

**Pull request closed without merging**
