### PR TITLE
You guys forgot to change to load webp box images.

### PR DESCRIPTION
**Pull request by Mou-Ikkai**
As the title says, plus image compression to the favicon.
(I noticed an error in Inspect Element of the box PNGs not being available, and it's because they're all WebPs now! So I made it now load the WebPs.)

### CODE REVIEW

**Review by vtheskeleton — CHANGES_REQUESTED** [review]
You deleted required icons?

**Review by Vukkyy — APPROVED** [review]
No

**Comment by Mou-Ikkai** [comment]
> You deleted required icons?

You tell us to read that lower health means better ranks, now I tell you to read descriptions for better understanding.

**Comment by vtheskeleton** [comment]
> > You deleted required icons?
> 
> You tell us to read that lower health means better ranks, now I tell you to read descriptions for better understanding.

banned for toxic

**Comment by vtheskeleton** [comment]
wont merge for that

**Pull request merged**
